import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import { Provider } from "react-redux";
import store from "@/lib/redux/store"; // Adjust this path based on your structure
import "./globals.css";

const JetBrainsFont = JetBrains_Mono({
  subsets: ["cyrillic"],
  weight: "400",
  variable: "--font-JetBrainsMono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Provider store={store}>
        <body className={`${JetBrainsFont.variable}`}>{children}</body>
      </Provider>
    </html>
  );
}
