import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";

import "./globals.css";
import ReduxProvider from "@/components/wrappers/Redux";

const JetBrainsFont = JetBrains_Mono({
  subsets: ["cyrillic"],
  weight: "400",
  variable: "--font-JetBrainsMono",
});

export const metadata: Metadata = {
  title: "AMO's Profile",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${JetBrainsFont.variable}`}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
